# LiteLLM Deployment Bundle
# Requires: llm-secrets Secret to be deployed first (see llm-secrets-bundle.yaml)
kind: Bundle
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: litellm
spec:
  resources:
  - content: |-
      ---
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: litellm
        namespace: default
      spec:
        replicas: {{ .Values.litellm.replicas }}
        selector:
          matchLabels:
            app: litellm
        template:
          metadata:
            labels:
              app: litellm
          spec:
            affinity:
              podAntiAffinity:
                preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    labelSelector:
                      matchLabels:
                        app: litellm
                    topologyKey: kubernetes.io/hostname
            containers:
            - name: litellm
              image: {{ .Values.images.litellm.repository }}:{{ .Values.images.litellm.tag }}
              command: ["litellm", "--config", "/app/config.yaml"]
              ports:
              - containerPort: 4000
                name: http
              env:
              - name: LITELLM_MASTER_KEY
                valueFrom:
                  secretKeyRef:
                    name: llm-secrets
                    key: LITELLM_MASTER_KEY
              - name: OPENAI_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: llm-secrets
                    key: OPENAI_API_KEY
              resources:
                requests:
                  memory: {{ .Values.litellm.resources.requests.memory | quote }}
                  cpu: {{ .Values.litellm.resources.requests.cpu | quote }}
                limits:
                  memory: {{ .Values.litellm.resources.limits.memory | quote }}
                  cpu: {{ .Values.litellm.resources.limits.cpu | quote }}
              livenessProbe:
                httpGet:
                  path: /health/liveliness
                  port: 4000
                initialDelaySeconds: 10
                periodSeconds: 15
                timeoutSeconds: 5
                failureThreshold: 3
              readinessProbe:
                httpGet:
                  path: /health/readiness
                  port: 4000
                initialDelaySeconds: 5
                periodSeconds: 10
                timeoutSeconds: 5
                failureThreshold: 3
              volumeMounts:
              - name: config-volume
                mountPath: /app/config.yaml
                subPath: config.yaml
            volumes:
            - name: config-volume
              configMap:
                name: litellm-config
      ---
      apiVersion: v1
      kind: Service
      metadata:
        name: litellm-service
        namespace: default
        labels:
          app: litellm
      spec:
        selector:
          app: litellm
        ports:
        - name: http
          protocol: TCP
          port: 4000
          targetPort: 4000
    name: litellm.yaml
  dependsOn:
  - name: llm-secrets
  - name: litellm-config
  targets:
  - clusterSelector:
      matchExpressions:
      - key: clusterclass-name.fleet.addons.cluster.x-k8s.io
        operator: In
        values:
        - docker-llm-clusterclass
