# This bundle deploys a template Secret to workload clusters.
# Users should update the secret values after deployment or pre-create the secret manually.
#
# The secret contains:
# - LITELLM_MASTER_KEY: Master key for LiteLLM API authentication
# - OPENAI_API_KEY: OpenAI API key (if using hybrid routing with OpenAI)
#
# To update the secret on a workload cluster after deployment:
#   kubectl create secret generic llm-secrets \
#     --from-literal=LITELLM_MASTER_KEY=your-secure-key \
#     --from-literal=OPENAI_API_KEY=sk-your-openai-key \
#     --dry-run=client -o yaml | kubectl apply -f -
#
kind: Bundle
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: llm-secrets
spec:
  resources:
  - content: |-
      ---
      apiVersion: v1
      kind: Secret
      metadata:
        name: llm-secrets
        namespace: default
        annotations:
          description: "LLM stack secrets - update with real values for production"
      type: Opaque
      stringData:
        # LiteLLM master key for API authentication
        # IMPORTANT: Change this to a secure value in production!
        LITELLM_MASTER_KEY: "change-me-in-production"
        # OpenAI API key for hybrid routing (optional)
        # Set to a real key if using OpenAI models
        OPENAI_API_KEY: "sk-placeholder-change-me"
    name: llm-secrets.yaml
  targets:
  - clusterSelector:
      matchExpressions:
      - key: clusterclass-name.fleet.addons.cluster.x-k8s.io
        operator: In
        values:
        - docker-llm-clusterclass
