kind: Bundle
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: ollama
spec:
  resources:
  - content: |-
      ---
      apiVersion: serving.knative.dev/v1
      kind: Service
      metadata:
        name: ollama
        namespace: default
      spec:
        template:
          metadata:
            annotations:
              autoscaling.knative.dev/min-scale: {{ .Values.ollama.autoscaling.minScale | quote }}
              autoscaling.knative.dev/max-scale: {{ .Values.ollama.autoscaling.maxScale | quote }}
              autoscaling.knative.dev/metric: "concurrency"
              autoscaling.knative.dev/target: {{ .Values.ollama.autoscaling.target | quote }}
              autoscaling.knative.dev/window: {{ .Values.ollama.autoscaling.window | quote }}
            labels:
              app: ollama
          spec:
            terminationGracePeriodSeconds: 30
            containers:
            - name: ollama
              image: {{ .Values.images.ollama.repository }}:{{ .Values.images.ollama.tag }}
              ports:
              - name: http1
                containerPort: 11434
              command: ["/bin/sh", "/startup.sh"]
              volumeMounts:
              - name: startup-script
                mountPath: /startup.sh
                subPath: startup.sh
              - name: ollama-data
                mountPath: /root/.ollama
              resources:
                requests:
                  cpu: {{ .Values.ollama.resources.requests.cpu | quote }}
                  memory: {{ .Values.ollama.resources.requests.memory | quote }}
                limits:
                  cpu: {{ .Values.ollama.resources.limits.cpu | quote }}
                  memory: {{ .Values.ollama.resources.limits.memory | quote }}
              readinessProbe:
                exec:
                  command:
                  - /bin/sh
                  - -c
                  - test -f /tmp/model_ready
                initialDelaySeconds: 10
                periodSeconds: 10
                failureThreshold: 60
            volumes:
            - name: startup-script
              configMap:
                name: ollama-startup-script
                defaultMode: 0755
            - name: ollama-data
              emptyDir: {}
        traffic:
        - percent: 100
          latestRevision: true
      ---
      apiVersion: v1
      kind: Service
      metadata:
        name: ollama-service
        namespace: default
      spec:
        selector:
          app: ollama
        ports:
        - protocol: TCP
          port: 11434
          targetPort: 11434
    name: ollama.yaml
  dependsOn:
  - name: ollama-startup-config
  - name: knative-serving-core-part-1
  targets:
  - clusterSelector:
      matchExpressions:
      - key: clusterclass-name.fleet.addons.cluster.x-k8s.io
        operator: In
        values:
        - docker-llm-clusterclass
