kind: Bundle
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: openwebui
spec:
  resources:
  - content: |-
      ---
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: openwebui
        namespace: default
      spec:
        replicas: {{ .Values.openwebui.replicas }}
        selector:
          matchLabels:
            app: openwebui
        template:
          metadata:
            labels:
              app: openwebui
          spec:
            containers:
            - name: openwebui
              image: {{ .Values.images.openwebui.repository }}:{{ .Values.images.openwebui.tag }}
              ports:
              - containerPort: 8080
              env:
              - name: OPENAI_API_BASE_URL
                value: "http://litellm-service:4000"
              - name: OPENAI_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: llm-secrets
                    key: LITELLM_MASTER_KEY
      ---
      apiVersion: v1
      kind: Service
      metadata:
        name: openwebui-service
        namespace: default
      spec:
        selector:
          app: openwebui
        ports:
        - port: 8080
          targetPort: 8080
    name: openwebui.yaml
  dependsOn:
  - name: llm-secrets
  - name: litellm
  targets:
  - clusterSelector:
      matchExpressions:
      - key: clusterclass-name.fleet.addons.cluster.x-k8s.io
        operator: In
        values:
        - docker-llm-clusterclass
